program = _{ SOI ~ ( statement | function_call ~ ";" )* ~ EOI }
statement = { "var" ~ ident ~ ":" ~ type ~ "=" ~ (number | function_call) ~ ";" }
reassignment = { ident ~ "=" ~ (number | function_call) ~ ";" }
type = { "HEX" | "DEC" | "BIN" }
function_call = { ident ~ "(" ~ parameter* ~ ")" }
parameter = { ASCII_ALPHA+ }
ident = @{ ASCII_ALPHA+ }
number = @{ ASCII_DIGIT+ }
WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
NEWLINE = _{ "\r\n" | "\n" }